apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: { app: nginx }
spec:
  replicas: 1
  selector: { matchLabels: { app: nginx } }
  template:
    metadata: { labels: { app: nginx } }
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels: { app: nginx }
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.202     # choose an IP inside your pool
  selector: { app: nginx }
  ports:
    - name: http
      port: 80
      targetPort: 80

